
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-10T09:59:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8d5bb7d0aa324e09a94489f50acdc2b59e90621",
 "version": "0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
